# Generated by Django 5.2.17 on 2026-09-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='Telefone / WhatsApp')),
                ('code', models.CharField(max_length=6, verbose_name='Código OTP (6 dígitos)')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas Incorretas')),
                ('is_used', models.BooleanField(default=False, verbose_name='Código Utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Código OTP WhatsApp',
                'verbose_name_plural': 'Códigos OTP WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
