# Generated by Django 5.2.17 on 2026-09-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome do Grupo / Solista')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Imagem / Logo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Grupo / Solista',
                'verbose_name_plural': 'Grupos e Solistas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Era / Comeback')),
                ('slug', models.SlugField(blank=True, max_length=160, verbose_name='Slug')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('banner_url', models.URLField(blank=True, max_length=500, verbose_name='URL do Banner Promocional')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eras', to='groups.kpopgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Era / Comeback',
                'verbose_name_plural': 'Eras e Comebacks',
                'ordering': ['-release_date', 'name'],
                'unique_together': {('group', 'slug')},
            },
        ),
    ]
