# Generated by Django 5.2.17 on 2026-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='era',
            name='color_hex',
            field=models.CharField(blank=True, default='', help_text='Cor predominante da Era (ex: #EC4899), extraída automaticamente ou personalizada.', max_length=7, verbose_name='Cor Tema da Era (Hex)'),
        ),
    ]
