# Generated by Django 5.2.17 on 2026-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_era_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpopgroup',
            name='color_hex',
            field=models.CharField(blank=True, default='', help_text='Cor predominante do Grupo (ex: #EC4899), extraída automaticamente ou personalizada.', max_length=7, verbose_name='Cor Tema do Grupo (Hex)'),
        ),
    ]
