# Generated by Django 5.2.17 on 2026-09-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_populate_era_group_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Integrante')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.kpopgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Integrante / Membro',
                'verbose_name_plural': 'Integrantes / Membros',
                'ordering': ['order', 'id'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
