# Generated by Django 5.2.17 on 2026-09-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Slot (R$)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Status do Slot')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
            ],
            options={
                'verbose_name': 'Slot de Item',
                'verbose_name_plural': 'Slots de Itens',
                'ordering': ['set__set_number', 'item_definition__order_index', 'item_definition__name'],
            },
        ),
        migrations.CreateModel(
            name='CEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da CEG')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Regras de frete (nacional/internacional), prazos e avisos aos participantes.', verbose_name='Regras e Informações da CEG')),
                ('banner_url', models.URLField(blank=True, max_length=500, verbose_name='URL do Banner da CEG')),
                ('pix_key', models.CharField(blank=True, max_length=150, verbose_name='Chave Pix do Organizador')),
                ('pix_instructions', models.TextField(blank=True, help_text='Orientações como envio de comprovante, identificação no Pix, etc.', verbose_name='Instruções para Pagamento Pix')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendada (Standby / Countdown)'), ('OPEN', 'Aberta para Reservas'), ('CLOSED', 'Encerrada'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('opens_at', models.DateTimeField(blank=True, help_text='Se preenchido com data futura, a página pública exibirá o cronômetro regressivo.', null=True, verbose_name='Data e Hora de Abertura (Standby / Countdown)')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Encerramento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cegs', to='groups.era', verbose_name='Era / Comeback')),
            ],
            options={
                'verbose_name': 'CEG (Compra em Grupo)',
                'verbose_name_plural': 'CEGs (Compras em Grupo)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CEGItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Item')),
                ('member_name', models.CharField(blank=True, help_text='Usado para análises de popularidade e tempo de esgotamento', max_length=100, verbose_name='Integrante (se aplicável)')),
                ('item_type', models.CharField(choices=[('PHOTOCARD', 'Photocard'), ('POB', 'Pre-Order Benefit (POB)'), ('ALBUM', 'Álbum'), ('INCLUSION', 'Inclusão / Avulso'), ('OTHER', 'Outro')], default='PHOTOCARD', max_length=20, verbose_name='Tipo do Item')),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Padrão (R$)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Foto / Prévia')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ceg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_definitions', to='cegs.ceg', verbose_name='CEG')),
            ],
            options={
                'verbose_name': 'Definição de Item da CEG',
                'verbose_name_plural': 'Definições de Itens da CEG',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CEGSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(default=1, verbose_name='Número do Set')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo para Reservas')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Anotações do Set')),
                ('ceg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='cegs.ceg', verbose_name='CEG')),
            ],
            options={
                'verbose_name': 'Set da CEG',
                'verbose_name_plural': 'Sets da CEG',
                'ordering': ['set_number'],
            },
        ),
    ]
