# Generated by Django 5.2.17 on 2026-09-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cegs', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslot',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slots', to='participants.participant', verbose_name='Reservado por'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='item_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cegs.cegitemdefinition', verbose_name='Item Definido'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cegs.cegset', verbose_name='Set'),
        ),
        migrations.AlterUniqueTogether(
            name='cegset',
            unique_together={('ceg', 'set_number')},
        ),
        migrations.AlterUniqueTogether(
            name='itemslot',
            unique_together={('set', 'item_definition')},
        ),
    ]
