# Generated by Django 5.2.17 on 2026-09-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Ordem da Tentativa (Chegada)')),
                ('participant_name', models.CharField(max_length=150, verbose_name='Nome do Participante')),
                ('phone', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('social_handle', models.CharField(blank=True, max_length=100, verbose_name='@ Rede Social')),
                ('result', models.CharField(choices=[('SUCCESS', '1º Lugar (Reserva Garantida)'), ('LOST_RACE', 'Perdeu por Concorrência'), ('STANDBY_BLOCKED', 'Bloqueado (Modo Standby)'), ('ERROR', 'Erro / Falha')], max_length=30, verbose_name='Resultado')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes da Tentativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora Exata')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='cegs.itemslot', verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'Log de Tentativa de Claim',
                'verbose_name_plural': 'Logs de Tentativas de Claim (Ordem de Chegada)',
                'ordering': ['slot', 'attempt_number'],
            },
        ),
    ]
