# Generated by Django 5.2.17 on 2026-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0003_claimattemptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceg',
            name='frete_inter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do frete internacional (começa nulo e depois atualiza).', max_digits=10, null=True, verbose_name='Frete Internacional (R$)'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='prazo_pagamento_frete_inter',
            field=models.DateTimeField(blank=True, help_text='Data e hora limite para pagamento do frete internacional (opcional).', null=True, verbose_name='Prazo de Pagamento do Frete Inter'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='prazo_pagamento_item',
            field=models.DateTimeField(blank=True, help_text='Data e hora limite para pagamento do valor do item (opcional).', null=True, verbose_name='Prazo de Pagamento do Item'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='prazo_pagamento_taxa_aduaneira',
            field=models.DateTimeField(blank=True, help_text='Data e hora limite para pagamento da taxa aduaneira (opcional).', null=True, verbose_name='Prazo de Pagamento da Taxa Aduaneira'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='taxa_aduaneira',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da taxa aduaneira / alfandegária (começa nulo e depois atualiza).', max_digits=10, null=True, verbose_name='Taxa Aduaneira (R$)'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='is_frete_inter_paid',
            field=models.BooleanField(default=False, help_text='Check mark indicando se o frete internacional foi pago.', verbose_name='Frete Inter Pago'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='is_frete_nacional_paid',
            field=models.BooleanField(default=False, help_text='Check mark indicando se o frete nacional foi pago.', verbose_name='Frete Nacional Pago'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='is_item_paid',
            field=models.BooleanField(default=False, help_text='Check mark indicando se o valor do item foi pago.', verbose_name='Item Pago'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='is_taxa_aduaneira_paid',
            field=models.BooleanField(default=False, help_text='Check mark indicando se a taxa aduaneira foi paga.', verbose_name='Taxa Aduaneira Paga'),
        ),
    ]
