# Generated by Django 5.2.17 on 2026-09-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0004_ceg_frete_inter_ceg_prazo_pagamento_frete_inter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Caixa / Remessa')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('origem', models.CharField(choices=[('KR', 'Coreia do Sul (KR)'), ('JP', 'Japão (JP / Mercari)'), ('CN', 'China (CN)'), ('US', 'Estados Unidos (US)'), ('OTHER', 'Outro')], db_index=True, default='KR', max_length=10, verbose_name='Origem da Remessa')),
                ('status', models.CharField(choices=[('EM_CONSOLIDACAO', 'Em Consolidação (No armazém)'), ('PRONTA_ENVIO', 'Embalada (Pronta para envio)'), ('ENVIADA', 'Enviada (Em trânsito internacional)'), ('NO_BRASIL', 'No Brasil (Fiscalização aduaneira)'), ('TRIBUTADA', 'Tributada (Aguardando taxa)'), ('LIBERADA', 'Liberada pela alfândega (A caminho)'), ('ENTREGUE', 'Entregue ao organizador (Em triagem)'), ('FINALIZADA', 'Finalizada (Envios nacionais concluídos)')], db_index=True, default='EM_CONSOLIDACAO', max_length=30, verbose_name='Status do Envio')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio')),
                ('transportadora', models.CharField(blank=True, help_text='Ex: Correios / EMS, K-Packet, FedEx, DHL, etc.', max_length=100, verbose_name='Transportadora / Modalidade')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento no Brasil')),
                ('frete_inter_total', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total pago pelo frete internacional desta caixa.', max_digits=10, null=True, verbose_name='Frete Internacional Total (R$)')),
                ('taxa_aduaneira_total', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total pago em impostos/taxas alfandegárias desta caixa.', max_digits=10, null=True, verbose_name='Taxa Aduaneira Total (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Anotações Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Caixa (Remessa Internacional)',
                'verbose_name_plural': 'Caixas (Remessas Internacionais)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ceg',
            name='shipping_status',
            field=models.CharField(choices=[('EM_CONSOLIDACAO', 'Em Consolidação (No armazém)'), ('PRONTA_ENVIO', 'Embalada (Pronta para envio)'), ('ENVIADA', 'Enviada (Em trânsito internacional)'), ('NO_BRASIL', 'No Brasil (Fiscalização aduaneira)'), ('TRIBUTADA', 'Tributada (Aguardando taxa)'), ('LIBERADA', 'Liberada pela alfândega (A caminho)'), ('ENTREGUE', 'Entregue ao organizador (Em triagem)'), ('FINALIZADA', 'Finalizada (Envios nacionais concluídos)')], db_index=True, default='EM_CONSOLIDACAO', help_text='Sincronizado automaticamente com a Caixa vinculada.', max_length=30, verbose_name='Status de Envio'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cegs', to='cegs.caixa', verbose_name='Caixa / Remessa'),
        ),
    ]
