# Generated by Django 5.2.17 on 2026-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0005_caixa_ceg_shipping_status_ceg_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='frete_inter_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo total pago pelo frete internacional desta caixa.', max_digits=12, null=True, verbose_name='Frete Internacional Total (R$)'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='taxa_aduaneira_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo total pago em impostos/taxas alfandegárias desta caixa.', max_digits=12, null=True, verbose_name='Taxa Aduaneira Total (R$)'),
        ),
    ]
