# Generated by Django 5.2.17 on 2026-09-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0006_alter_caixa_frete_inter_total_and_more'),
        ('participants', '0003_participantnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome / Descrição do Item')),
                ('link_pedido', models.URLField(blank=True, max_length=600, verbose_name='Link do Pedido (Mercari, etc.)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('foto_arquivo', models.FileField(blank=True, null=True, upload_to='itens_individuais/%Y/%m/', verbose_name='Arquivo de Foto')),
                ('foto_url', models.CharField(blank=True, max_length=600, verbose_name='URL Externa da Foto')),
                ('status', models.CharField(choices=[('COMPRADO', 'Comprado'), ('WAREHOUSE', 'Na Warehouse (Armazém)'), ('EM_CONSOLIDACAO', 'Em Consolidação'), ('ENVIADO', 'Enviado / Em Trânsito'), ('NO_BRASIL', 'No Brasil / Fiscalização'), ('TRIBUTADO', 'Tributado'), ('LIBERADO', 'Liberado pela Alfândega'), ('NA_GOM', 'Chegou na GOM (Organizador)'), ('FINALIZADO', 'Entregue / Finalizado')], db_index=True, default='COMPRADO', max_length=30, verbose_name='Status do Item')),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, help_text='Preço pago no produto.', max_digits=10, null=True, verbose_name='Preço do Produto (R$)')),
                ('frete_inter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frete Internacional (R$)')),
                ('frete_inter_pago', models.BooleanField(default=False, verbose_name='Frete Inter Pago?')),
                ('prazo_frete_inter', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Frete Inter')),
                ('taxa_aduaneira', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa Aduaneira (R$)')),
                ('taxa_aduaneira_paga', models.BooleanField(default=False, verbose_name='Taxa Aduaneira Paga?')),
                ('prazo_taxa_aduaneira', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Taxa Aduaneira')),
                ('observacoes', models.TextField(blank=True, verbose_name='Anotações Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_individuais', to='cegs.caixa', verbose_name='Caixa / Remessa')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_individuais', to='participants.participant', verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Item Individual (Mercari)',
                'verbose_name_plural': 'Itens Individuais (Mercari)',
                'ordering': ['-created_at'],
            },
        ),
    ]
