# Generated by Django 5.2.17 on 2026-09-12 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0007_itemindividual'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itemslot',
            name='frete_inter_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do frete rateado especificamente para este slot pela Caixa.', max_digits=10, null=True, verbose_name='Frete Inter Específico (R$)'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='prazo_frete_inter',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Frete Inter'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='prazo_taxa_aduaneira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Taxa Aduaneira'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='taxa_aduaneira_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da taxa aduaneira rateada especificamente para este slot pela Caixa.', max_digits=10, null=True, verbose_name='Taxa Aduaneira Específica (R$)'),
        ),
        migrations.AddField(
            model_name='cegitemdefinition',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_definitions', to='cegs.tipoitem', verbose_name='Tipo de Item (Dinâmico)'),
        ),
        migrations.AddField(
            model_name='itemindividual',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_individuais', to='cegs.tipoitem', verbose_name='Tipo de Item'),
        ),
        migrations.CreateModel(
            name='CaixaItemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frete Internacional Unitário (R$)')),
                ('taxa_unitaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa Aduaneira Unitária (R$)')),
                ('prazo_frete', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Frete Inter')),
                ('prazo_taxa', models.DateTimeField(blank=True, null=True, verbose_name='Prazo Pagamento Taxa Aduaneira')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rates', to='cegs.caixa', verbose_name='Caixa / Remessa')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_rates', to='cegs.tipoitem', verbose_name='Tipo de Item')),
            ],
            options={
                'verbose_name': 'Taxa por Tipo de Item na Caixa',
                'verbose_name_plural': 'Taxas por Tipos de Itens na Caixa',
                'ordering': ['tipo_item__nome'],
                'unique_together': {('caixa', 'tipo_item')},
            },
        ),
    ]
