# Generated by Django 5.2.17 on 2026-09-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0009_seed_tipos_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='prazo_frete',
            field=models.DateTimeField(blank=True, help_text='Data limite para os compradores pagarem o frete internacional desta caixa.', null=True, verbose_name='Prazo Pagamento Frete Internacional'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='prazo_taxa',
            field=models.DateTimeField(blank=True, help_text='Data limite para os compradores pagarem a taxa aduaneira desta caixa.', null=True, verbose_name='Prazo Pagamento Taxa Aduaneira'),
        ),
    ]
