# Generated by Antigravity on 2026-09-12
from django.db import migrations


def seed_standard_tipos_item(apps, schema_editor):
    TipoItem = apps.get_model('cegs', 'TipoItem')

    tipos = [
        ('Photocard', 'Cards colecionáveis (POBs, inclusões, sorteios, fansigns)'),
        ('POB', 'Pre-Order Benefit / Bônus de pré-venda exclusivo de loja'),
        ('Álbum', 'Álbuns completos, compactos ou versões de K-pop'),
        ('CD', 'CDs de música, jewel cases ou mini-álbuns'),
        ('Inclusão', 'Inclusões de álbuns (adesivos, postais, posters, bookmarks)'),
        ('Lucky Draw', 'Cards exclusivos de sorteios e eventos de loja'),
        ('Fansign', 'Benefícios de eventos de autógrafos ou videocalls'),
        ('Lightstick', 'Bastões de luz oficiais e acessórios de turnê'),
        ('Outro / Merch', 'Mercadorias oficiais e itens diversos'),
    ]

    for nome, desc in tipos:
        # Procura por versões existentes
        existing = TipoItem.objects.filter(nome__iexact=nome).first()
        if not existing:
            if nome == 'Álbum':
                existing = TipoItem.objects.filter(nome__icontains='lbum').first()
            elif nome == 'Inclusão':
                existing = TipoItem.objects.filter(nome__icontains='Inclus').first()

        if existing:
            existing.nome = nome
            existing.descricao = desc
            existing.save()
        else:
            TipoItem.objects.create(nome=nome, descricao=desc)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0011_alter_claimattemptlog_result_itemwaitinglist'),
    ]

    operations = [
        migrations.RunPython(seed_standard_tipos_item, reverse_func),
    ]
