# Generated by Django 5.2.17 on 2026-09-13 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0012_seed_standard_tipos_item'),
        ('participants', '0004_alter_participantnotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, db_index=True, help_text='Ex: PAC-2026-0001 (gerado automaticamente se vazio)', max_length=50, unique=True, verbose_name='Identificador do Pacote')),
                ('status', models.CharField(choices=[('EM_PREPARACAO', 'Em Preparação / Embalando'), ('ENVIADO', 'Enviado Nacionalmente'), ('ENTREGUE', 'Entregue')], db_index=True, default='EM_PREPARACAO', max_length=20, verbose_name='Status do Pacote')),
                ('codigo_rastreio', models.CharField(blank=True, help_text='Ex: NL123456789BR, QD123456789BR', max_length=100, verbose_name='Código de Rastreio')),
                ('transportadora', models.CharField(blank=True, default='Correios', help_text='Ex: Mini Envios, Carta Registrada, PAC, Sedex, Jadlog', max_length=100, verbose_name='Transportadora / Modalidade')),
                ('valor_frete_nacional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Frete Nacional (R$)')),
                ('is_frete_pago', models.BooleanField(default=False, help_text='Indica se o participante já pagou o frete nacional deste pacote', verbose_name='Frete Nacional Pago?')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Anotações do Organizador / Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_nacionais', to='participants.participant', verbose_name='Destinatário (Joiner)')),
            ],
            options={
                'verbose_name': 'Pacote de Envio Nacional',
                'verbose_name_plural': 'Pacotes de Envios Nacionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itemindividual',
            name='pacote_nacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_individuais', to='cegs.pacotenacional', verbose_name='Pacote Nacional'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='pacote_nacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='cegs.pacotenacional', verbose_name='Pacote Nacional'),
        ),
    ]
