# Generated by Django 5.2.17 on 2026-09-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0013_pacotenacional_itemindividual_pacote_nacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemindividual',
            name='produto_pago',
            field=models.BooleanField(default=True, verbose_name='Produto / Item Pago?'),
        ),
    ]
