# Generated by Django 5.2.17 on 2026-09-18 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0015_reopen_cegs_with_available_slots'),
        ('participants', '0005_alter_participant_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACCOUNT_CREATED', 'Cadastro de Participante'), ('CLAIM_ATTEMPT', 'Tentativa de Claim'), ('CLAIM_SUCCESS', 'Claim Vencedor (Garantido)'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('PAYMENT_ITEM', 'Pagamento do Item'), ('PAYMENT_FRETE_INTER', 'Pagamento de Frete Internacional'), ('PAYMENT_TAXA', 'Pagamento de Taxa Aduaneira'), ('PAYMENT_FRETE_NACIONAL', 'Pagamento de Frete Nacional'), ('SLOT_ASSIGNED', 'Slot Vinculado Manualmente'), ('SLOT_RELEASED', 'Slot Desvinculado Manualmente'), ('OTHER', 'Outra Operação')], db_index=True, max_length=40, verbose_name='Tipo de Evento')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Operador')),
                ('participant_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Nome do Participante')),
                ('participant_phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='WhatsApp do Participante')),
                ('action_label', models.CharField(max_length=255, verbose_name='Ação / Descrição')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Campo Alterado')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Valor Anterior')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Novo Valor')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e Hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('ceg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cegs.ceg', verbose_name='CEG')),
                ('item_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cegs.itemindividual', verbose_name='Item Individual (Mercari)')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='participants.participant', verbose_name='Participante')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cegs.itemslot', verbose_name='Slot do Item')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
