# Generated by Django 5.2.17 on 2026-09-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0016_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='pacote_nacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='cegs.pacotenacional', verbose_name='Pacote Nacional'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='entregue_por',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('JOINER', 'Joiner / Participante')], default='ADMIN', max_length=20, verbose_name='Confirmado recebimento por'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='feedback_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Feedback'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nota de 1 a 5 dada pelo participante', null=True, verbose_name='Avaliação (1 a 5 estrelas)'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='feedback_texto',
            field=models.TextField(blank=True, help_text='Comentário ou depoimento do joiner após o recebimento', verbose_name='Feedback / Depoimento do Joiner'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Cadastro de Participante'), ('CLAIM_ATTEMPT', 'Tentativa de Claim'), ('CLAIM_SUCCESS', 'Claim Vencedor (Garantido)'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('PAYMENT_ITEM', 'Pagamento do Item'), ('PAYMENT_FRETE_INTER', 'Pagamento de Frete Internacional'), ('PAYMENT_TAXA', 'Pagamento de Taxa Aduaneira'), ('PAYMENT_FRETE_NACIONAL', 'Pagamento de Frete Nacional'), ('PACKAGE_SENT', 'Pacote Despachado / Enviado'), ('PACKAGE_DELIVERED', 'Pacote Entregue / Feedback Registrado'), ('SLOT_ASSIGNED', 'Slot Vinculado Manualmente'), ('SLOT_RELEASED', 'Slot Desvinculado Manualmente'), ('OTHER', 'Outra Operação')], db_index=True, max_length=40, verbose_name='Tipo de Evento'),
        ),
    ]
