# Generated by Django 5.2.17 on 2026-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0017_auditlog_pacote_nacional_pacotenacional_entregue_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacotenacional',
            name='cep_destinatario',
            field=models.CharField(blank=True, max_length=15, verbose_name='CEP de Destino'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='endereco_destinatario',
            field=models.TextField(blank=True, verbose_name='Endereço de Destino Informado'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='observacoes_joiner',
            field=models.TextField(blank=True, verbose_name='Observações / Preferências do Joiner'),
        ),
        migrations.AddField(
            model_name='pacotenacional',
            name='solicitado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Solicitação pelo Joiner'),
        ),
        migrations.AlterField(
            model_name='pacotenacional',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado pelo Joiner'), ('EM_PREPARACAO', 'Em Preparação / Embalando'), ('ENVIADO', 'Enviado Nacionalmente'), ('ENTREGUE', 'Entregue')], db_index=True, default='EM_PREPARACAO', max_length=20, verbose_name='Status do Pacote'),
        ),
    ]
