# Generated by Django 5.2.17 on 2026-09-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0018_pacotenacional_cep_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Cadastro de Participante'), ('CLAIM_ATTEMPT', 'Tentativa de Claim'), ('CLAIM_SUCCESS', 'Claim Vencedor (Garantido)'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('PAYMENT_ITEM', 'Pagamento do Item'), ('PAYMENT_FRETE_INTER', 'Pagamento de Frete Internacional'), ('PAYMENT_TAXA', 'Pagamento de Taxa Aduaneira'), ('PAYMENT_FRETE_NACIONAL', 'Pagamento de Frete Nacional'), ('PACKAGE_REQUESTED', 'Solicitação de Envio pelo Joiner'), ('PACKAGE_SENT', 'Pacote Despachado / Enviado'), ('PACKAGE_DELIVERED', 'Pacote Entregue / Feedback Registrado'), ('SLOT_ASSIGNED', 'Slot Vinculado Manualmente'), ('SLOT_RELEASED', 'Slot Desvinculado Manualmente'), ('OTHER', 'Outra Operação')], db_index=True, max_length=40, verbose_name='Tipo de Evento'),
        ),
    ]
