# Generated by Django 5.2.17 on 2026-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0019_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_formulario_google', models.URLField(blank=True, help_text='Link do Google Forms onde os joiners preenchem o endereço e preferências de envio nacional.', max_length=500, verbose_name='Link do Formulário de Envio (Google Forms)')),
                ('instrucoes_envio', models.TextField(blank=True, help_text='Instruções exibidas para os joiners ao solicitar envio nacional na Minha Caixinha.', verbose_name='Instruções / Informações de Envio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Envio Nacional',
                'verbose_name_plural': 'Configurações de Envio Nacional',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Cadastro de Participante'), ('CLAIM_ATTEMPT', 'Tentativa de Claim'), ('CLAIM_SUCCESS', 'Claim Vencedor (Garantido)'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('PAYMENT_ITEM', 'Pagamento do Item'), ('PAYMENT_FRETE_INTER', 'Pagamento de Frete Internacional'), ('PAYMENT_TAXA', 'Pagamento de Taxa Aduaneira'), ('PAYMENT_FRETE_NACIONAL', 'Pagamento de Frete Nacional'), ('PACKAGE_REQUESTED', 'Solicitação de Envio Nacional'), ('PACKAGE_SENT', 'Pacote Despachado / Enviado'), ('PACKAGE_DELIVERED', 'Pacote Entregue / Feedback Registrado'), ('SLOT_ASSIGNED', 'Slot Vinculado Manualmente'), ('SLOT_RELEASED', 'Slot Desvinculado Manualmente'), ('OTHER', 'Outra Operação')], db_index=True, max_length=40, verbose_name='Tipo de Evento'),
        ),
    ]
