# Generated by Django 5.2.17 on 2026-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0020_configuracaoenvio_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('EM_CONSOLIDACAO', 'Em Consolidação (No armazém)'), ('PRONTA_ENVIO', 'Embalada (Pronta para envio)'), ('ENVIADA', 'Enviada (Em trânsito internacional)'), ('NO_BRASIL', 'No Brasil (Fiscalização aduaneira)'), ('TRIBUTADA', 'Tributada (Aguardando taxa)'), ('LIBERADA', 'Liberada pela alfândega (A caminho)'), ('ENTREGUE', 'Chegou na casa da GOM'), ('FINALIZADA', 'Finalizada (Envios nacionais concluídos)')], db_index=True, default='EM_CONSOLIDACAO', max_length=30, verbose_name='Status do Envio'),
        ),
        migrations.AlterField(
            model_name='ceg',
            name='shipping_status',
            field=models.CharField(choices=[('EM_CONSOLIDACAO', 'Em Consolidação (No armazém)'), ('PRONTA_ENVIO', 'Embalada (Pronta para envio)'), ('ENVIADA', 'Enviada (Em trânsito internacional)'), ('NO_BRASIL', 'No Brasil (Fiscalização aduaneira)'), ('TRIBUTADA', 'Tributada (Aguardando taxa)'), ('LIBERADA', 'Liberada pela alfândega (A caminho)'), ('ENTREGUE', 'Chegou na casa da GOM'), ('FINALIZADA', 'Finalizada (Envios nacionais concluídos)')], db_index=True, default='EM_CONSOLIDACAO', help_text='Sincronizado automaticamente com a Caixa vinculada.', max_length=30, verbose_name='Status de Envio'),
        ),
    ]
