# Generated by Django 5.2.17 on 2026-09-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0021_alter_caixa_status_alter_ceg_shipping_status'),
        ('groups', '0004_populate_era_group_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVitrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Nome do Item')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Detalhes')),
                ('integrante', models.CharField(blank=True, max_length=100, verbose_name='Integrante')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade em Estoque')),
                ('condicao', models.CharField(choices=[('NOVO', 'Novo / Impecável'), ('MINT', 'Excelente Estado (Mint)'), ('COM_DETALHE', 'Com Detalhe / Marca de Fábrica')], default='NOVO', max_length=30, verbose_name='Condição do Item')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível à Pronta Entrega'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], db_index=True, default='DISPONIVEL', max_length=20, verbose_name='Status do Item')),
                ('image_url', models.URLField(blank=True, max_length=600, verbose_name='URL da Foto / Imagem')),
                ('foto_arquivo', models.FileField(blank=True, null=True, upload_to='vitrine/%Y/%m/', verbose_name='Arquivo de Foto')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na Vitrine')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vitrine', to='groups.era', verbose_name='Era / Comeback')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vitrine', to='groups.kpopgroup', verbose_name='Grupo / Solista')),
                ('origem_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vitrine', to='cegs.caixa', verbose_name='Caixa de Origem')),
                ('origem_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_vitrine', to='cegs.itemslot', verbose_name='Slot de Origem da CEG')),
                ('tipo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_vitrine', to='cegs.tipoitem', verbose_name='Tipo de Item')),
            ],
            options={
                'verbose_name': 'Item da Vitrine',
                'verbose_name_plural': 'Itens da Vitrine',
                'ordering': ['-destaque', '-created_at'],
            },
        ),
    ]
