# Generated by Django 5.2.17 on 2026-09-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0022_itemvitrine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvitrine',
            name='condicao',
        ),
    ]
