# Generated by Django 5.2.17 on 2026-09-19 12:47

import django.utils.timezone
from django.db import migrations, models


def run_backfill(apps, schema_editor):
    try:
        from apps.cegs.audit_service import AuditService
        AuditService.backfill_historical_logs()
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning(f"Erro ao executar backfill de logs na migração: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0023_remove_itemvitrine_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
        migrations.RunPython(run_backfill, reverse_code=migrations.RunPython.noop),
    ]
