# Generated by Django 5.2.17 on 2026-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0024_alter_auditlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cegitemdefinition',
            name='sub_category',
            field=models.CharField(blank=True, default='', help_text='Subcategoria do Photocard (ex: Regulares, Pob, LD, VCE, Broadcast)', max_length=50, verbose_name='Subcategoria'),
        ),
    ]
