# Generated by Django 5.2.17 on 2026-09-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0025_cegitemdefinition_sub_category'),
        ('participants', '0007_remove_participant_bairro_remove_participant_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Cadastro de Participante'), ('CLAIM_ATTEMPT', 'Tentativa de Claim'), ('CLAIM_SUCCESS', 'Claim Vencedor (Garantido)'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('PAYMENT_ITEM', 'Pagamento do Item'), ('PAYMENT_FRETE_INTER', 'Pagamento de Frete Internacional'), ('PAYMENT_TAXA', 'Pagamento de Taxa Aduaneira'), ('PAYMENT_FRETE_NACIONAL', 'Pagamento de Frete Nacional'), ('PACKAGE_REQUESTED', 'Solicitação de Envio Nacional'), ('PACKAGE_SENT', 'Pacote Despachado / Enviado'), ('PACKAGE_DELIVERED', 'Pacote Entregue / Feedback Registrado'), ('SLOT_ASSIGNED', 'Slot Vinculado Manualmente'), ('SLOT_RELEASED', 'Slot Desvinculado Manualmente'), ('POLLING_VOTE', 'Voto em Enquete de Demanda'), ('POLLING_CONVERTED', 'Conversão de Enquete em Set'), ('OTHER', 'Outra Operação')], db_index=True, max_length=40, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='ceg',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('POLLING', 'Em Enquete / Sondagem de Demanda'), ('SCHEDULED', 'Agendada (Standby / Countdown)'), ('OPEN', 'Aberta para Reservas'), ('CLOSED', 'Encerrada'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CEGInterestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Convertido em Slot')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Votado em')),
                ('ceg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_votes', to='cegs.ceg', verbose_name='CEG')),
                ('converted_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_vote', to='cegs.itemslot', verbose_name='Slot Convertido')),
                ('item_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_votes', to='cegs.cegitemdefinition', verbose_name='Item / Integrante')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceg_interest_votes', to='participants.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Voto de Interesse em CEG',
                'verbose_name_plural': 'Votos de Interesse em CEG',
                'ordering': ['created_at'],
                'unique_together': {('ceg', 'item_definition', 'participant')},
            },
        ),
    ]
