# Generated by Django 5.2.17 on 2026-09-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0026_alter_auditlog_event_type_alter_ceg_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvitrine',
            name='sub_category',
            field=models.CharField(blank=True, default='', help_text='Subcategoria do Photocard (ex: Regulares, Pob, LD, VCE, Broadcast, Fansign)', max_length=50, verbose_name='Subcategoria / Tipo de Photocard'),
        ),
    ]
