# Generated by Django 5.2.17 on 2026-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0027_itemvitrine_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemslot',
            options={'ordering': ['set__set_number', 'item_definition__order_index', 'item_definition__name', 'unit_number'], 'verbose_name': 'Slot de Item', 'verbose_name_plural': 'Slots de Itens'},
        ),
        migrations.AlterUniqueTogether(
            name='itemslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cegitemdefinition',
            name='is_avulso',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se o item possui estoque fixo/individual e não deve ser replicado em novos sets', verbose_name='Item Avulso (Não replica em sets)'),
        ),
        migrations.AddField(
            model_name='cegitemdefinition',
            name='quantidade_avulsa',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade física de unidades deste item avulso', verbose_name='Quantidade Disponível'),
        ),
        migrations.AddField(
            model_name='cegset',
            name='is_avulso',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se este container armazena os itens avulsos da CEG', verbose_name='Set de Itens Avulsos'),
        ),
        migrations.AddField(
            model_name='itemslot',
            name='unit_number',
            field=models.PositiveIntegerField(default=1, help_text='Identificador sequencial da unidade física do item neste set/avulso', verbose_name='Número da Unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='itemslot',
            unique_together={('set', 'item_definition', 'unit_number')},
        ),
    ]
