# Generated by Django 5.2.17 on 2026-10-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0028_alter_itemslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='pix_instructions_frete',
            field=models.TextField(blank=True, help_text='Orientações específicas para o pagamento do frete desta caixa.', verbose_name='Instruções Pix para Frete'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pix_instructions_taxa',
            field=models.TextField(blank=True, help_text='Orientações específicas para o pagamento da taxa aduaneira desta caixa.', verbose_name='Instruções Pix para Taxa'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pix_key_frete',
            field=models.CharField(blank=True, help_text='Chave Pix específica para arrecadar o frete internacional desta caixa.', max_length=150, verbose_name='Chave Pix para Frete da Caixa'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='pix_key_taxa',
            field=models.CharField(blank=True, help_text='Chave Pix específica para arrecadar a taxa aduaneira desta caixa.', max_length=150, verbose_name='Chave Pix para Taxa da Caixa'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='pix_instructions_frete',
            field=models.TextField(blank=True, help_text='Orientações específicas para o pagamento do frete internacional.', verbose_name='Instruções Pix para Frete'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='pix_instructions_taxa',
            field=models.TextField(blank=True, help_text='Orientações específicas para o pagamento da taxa aduaneira.', verbose_name='Instruções Pix para Taxa'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='pix_key_frete',
            field=models.CharField(blank=True, help_text='Chave Pix específica para Frete Internacional (se vazio, usa a chave padrão).', max_length=150, verbose_name='Chave Pix para Frete Internacional'),
        ),
        migrations.AddField(
            model_name='ceg',
            name='pix_key_taxa',
            field=models.CharField(blank=True, help_text='Chave Pix específica para Taxa Aduaneira (se vazio, usa a chave padrão).', max_length=150, verbose_name='Chave Pix para Taxa Aduaneira'),
        ),
    ]
