# Generated by Django 5.2.17 on 2026-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0029_caixa_pix_instructions_frete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_light_url', models.URLField(blank=True, max_length=500, verbose_name='URL do Banner (Modo Claro)')),
                ('banner_dark_url', models.URLField(blank=True, max_length=500, verbose_name='URL do Banner (Modo Escuro)')),
                ('alt_text', models.CharField(default='ValCegs Masterlist', max_length=200, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Banner da Home',
                'verbose_name_plural': 'Configurações de Banners da Home',
            },
        ),
    ]
