# Generated by Django 5.2.17 on 2026-10-09 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cegs', '0030_homebannerconfig'),
        ('participants', '0008_alter_claim_claimed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CLAIM', 'Claim / Reserva de Photocard'), ('PACKAGE_REQUEST', 'Solicitação de Envio Nacional'), ('PAYMENT', 'Pagamento Registrado'), ('CLAIM_CANCELLED', 'Claim Cancelado / Liberado'), ('POLLING', 'Voto / Demanda em Enquete'), ('ACCOUNT', 'Novo Cadastro de Joiner'), ('SYSTEM', 'Aviso Operacional')], db_index=True, default='SYSTEM', max_length=40, verbose_name='Tipo de Notificação')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem / Detalhes')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='URL de Ação')),
                ('action_label', models.CharField(blank=True, default='Ver Detalhes', max_length=80, verbose_name='Texto do Botão')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gom_notifications', to='cegs.auditlog', verbose_name='Log de Auditoria Origem')),
                ('ceg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gom_notifications', to='cegs.ceg', verbose_name='CEG')),
                ('pacote_nacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gom_notifications', to='cegs.pacotenacional', verbose_name='Pacote Nacional')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gom_notifications', to='participants.participant', verbose_name='Participante')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gom_notifications', to='cegs.itemslot', verbose_name='Slot do Item')),
            ],
            options={
                'verbose_name': 'Notificação da GOM',
                'verbose_name_plural': 'Notificações da GOM',
                'ordering': ['-created_at'],
            },
        ),
    ]
