# Generated by Django 5.2.17 on 2026-09-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cegs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Participante')),
                ('whatsapp', models.CharField(db_index=True, help_text='Apenas números com DDD e DDI (ex: 5511999998888)', max_length=30, unique=True, verbose_name='WhatsApp')),
                ('social_handle', models.CharField(blank=True, help_text='Identificador público na comunidade de K-pop (ex: @jihyolover)', max_length=100, verbose_name='@ Rede Social (Twitter / Instagram)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas do Organizador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Pagamento'), ('PAID', 'Pago / Confirmado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Pagamento')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Reserva (R$)')),
                ('payment_proof_url', models.URLField(blank=True, max_length=500, verbose_name='Link do Comprovante (Pix/Drive)')),
                ('participant_notes', models.TextField(blank=True, verbose_name='Observações do Participante')),
                ('organizer_notes', models.TextField(blank=True, verbose_name='Notas do Organizador')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='Reservado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação do Pagamento')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='cegs.itemslot', verbose_name='Slot Reservado')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='participants.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Reserva (Claim)',
                'verbose_name_plural': 'Reservas (Claims)',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
