# Generated by Django 5.2.17 on 2026-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(blank=True, help_text='Como você prefere ser chamado(a) no sistema (ex: Bia, Hudo, JihyoStan)', max_length=60, verbose_name='Nome de Usuário / Apelido'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome Completo do Participante'),
        ),
    ]
