# Generated by Django 5.2.17 on 2026-09-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_username_alter_participant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem / Detalhes')),
                ('notification_type', models.CharField(choices=[('SET_CANCELLED', 'Set Cancelado'), ('CLAIM_UPDATE', 'Atualização de Reserva'), ('GENERAL', 'Aviso Geral')], db_index=True, default='SET_CANCELLED', max_length=40, verbose_name='Tipo de Notificação')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='participants.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Notificação de Participante',
                'verbose_name_plural': 'Notificações de Participantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
