# Generated by Django 5.2.17 on 2026-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participantnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantnotification',
            name='notification_type',
            field=models.CharField(choices=[('SET_CANCELLED', 'Set Cancelado'), ('CLAIM_UPDATE', 'Atualização de Reserva'), ('GENERAL', 'Aviso Geral'), ('ENVIO_NACIONAL', 'Envio Nacional Despachado')], db_index=True, default='SET_CANCELLED', max_length=40, verbose_name='Tipo de Notificação'),
        ),
    ]
