# Generated by Django 5.2.17 on 2026-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participantnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='whatsapp',
            field=models.CharField(db_index=True, help_text='Apenas números com DDD e DDI (ex: 5511999998888 ou 12025550199)', max_length=30, unique=True, verbose_name='WhatsApp'),
        ),
    ]
