# Generated by Django 5.2.17 on 2026-09-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='participant',
            name='cep',
            field=models.CharField(blank=True, max_length=15, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='participant',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='participant',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento / Apto'),
        ),
        migrations.AddField(
            model_name='participant',
            name='estado',
            field=models.CharField(blank=True, max_length=10, verbose_name='UF / Estado'),
        ),
        migrations.AddField(
            model_name='participant',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rua / Logradouro'),
        ),
        migrations.AddField(
            model_name='participant',
            name='numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número'),
        ),
    ]
