# Generated by Django 5.2.17 on 2026-09-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_participant_bairro_participant_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='numero',
        ),
    ]
