# Generated by Django 5.2.17 on 2026-10-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_remove_participant_bairro_remove_participant_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Reservado em'),
        ),
    ]
